export const TOKEN_EXPIRED = 'TOKEN_EXPIRED'
export const INVALID_TOKEN = 'INVALID_TOKEN'
export const INVALID_REFRESH_TOKEN = 'INVALID REFRESH TOKEN'
export const INVALID_USER_REFRESH_TOKEN = 'INVALID USER REFRESH TOKEN'
export const COOK_ACCESS_TOKEN = 'access_token'
export const COOK_REFRESH_TOKEN = 'refresh_token'
export const FAIL_REFRESH_TOKEN = 'Fail to refresh token'
